sectors = [
    "Energy",
    "Materials",
    "Industrials",
    "Consumer Discretionary",
    "Consumer Staples",
    "Health Care",
    "Financials",
    "Information Technology",
    "Communication Services",
    "Utilities",
    "Real Estate"
]

country_region = {
    # North America
    "United States": "North America",
    "Canada": "North America",
    "Mexico": "North America",

    # Latin America
    "Brazil": "Latin America",
    "Argentina": "Latin America",
    "Chile": "Latin America",
    "Colombia": "Latin America",
    "Peru": "Latin America",

    # Europe
    "United Kingdom": "Europe",
    "Germany": "Europe",
    "France": "Europe",
    "Italy": "Europe",
    "Spain": "Europe",
    "Netherlands": "Europe",
    "Switzerland": "Europe",
    "Sweden": "Europe",
    "Norway": "Europe",
    "Denmark": "Europe",
    "Poland": "Europe",
    "Austria": "Europe",
    "Finland": "Europe",

    # Middle East & Africa
    "South Africa": "Middle East & Africa",
    "Saudi Arabia": "Middle East & Africa",
    "United Arab Emirates": "Middle East & Africa",
    "Qatar": "Middle East & Africa",
    "Egypt": "Middle East & Africa",
    "Nigeria": "Middle East & Africa",
    "Israel": "Middle East & Africa",
    "Turkey": "Middle East & Africa",

    # Asia-Pacific (Developed)
    "Japan": "Asia-Pacific",
    "Australia": "Asia-Pacific",
    "New Zealand": "Asia-Pacific",
    "Hong Kong": "Asia-Pacific",
    "Singapore": "Asia-Pacific",
    "South Korea": "Asia-Pacific",

    # Asia-Pacific (Emerging)
    "China": "Asia-Pacific",
    "India": "Asia-Pacific",
    "Indonesia": "Asia-Pacific",
    "Malaysia": "Asia-Pacific",
    "Philippines": "Asia-Pacific",
    "Thailand": "Asia-Pacific",
    "Vietnam": "Asia-Pacific",
    "Pakistan": "Asia-Pacific",
}

currencies = [
    'USD',  # US Dollar
    'EUR',  # Euro
    'GBP',  # British Pound Sterling
    'JPY',  # Japanese Yen
    'AUD',  # Australian Dollar
    'CAD',  # Canadian Dollar
    'CHF',  # Swiss Franc
    'CNY',  # Chinese Yuan Renminbi
    'INR',  # Indian Rupee
    'BRL',  # Brazilian Real
    'RUB',  # Russian Ruble
    'ZAR',  # South African Rand
    'NZD',  # New Zealand Dollar
    'SGD',  # Singapore Dollar
    'KRW',  # South Korean Won
    'MXN',  # Mexican Peso
    'HKD',  # Hong Kong Dollar
    'SEK',  # Swedish Krona
    'NOK',  # Norwegian Krone
    'DKK',  # Danish Krone
    'PLN',  # Polish Zloty
    'TRY',  # Turkish Lira
    'THB',  # Thai Baht
    'MYR',  # Malaysian Ringgit
]

companies = [
    {"name": "NVIDIA Corporation", "ticker": "NVDA", "country": "USA", "sector": "Information Technology",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Microsoft Corporation", "ticker": "MSFT", "country": "USA", "sector": "Information Technology",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Apple Inc.", "ticker": "AAPL", "country": "USA", "sector": "Information Technology", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Alphabet Inc. (Google)", "ticker": "GOOG", "country": "USA", "sector": "Communication Services",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Amazon.com, Inc.", "ticker": "AMZN", "country": "USA", "sector": "Consumer Discretionary",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Meta Platforms, Inc.", "ticker": "META", "country": "USA", "sector": "Communication Services",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Broadcom Inc.", "ticker": "AVGO", "country": "USA", "sector": "Information Technology", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Saudi Aramco", "ticker": "2222.SR", "country": "Saudi Arabia", "sector": "Energy", "currency": "SAR",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Tesla, Inc.", "ticker": "TSLA", "country": "USA", "sector": "Consumer Discretionary", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Berkshire Hathaway", "ticker": "BRK.A", "country": "USA", "sector": "Financials", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Johnson & Johnson", "ticker": "JNJ", "country": "USA", "sector": "Health Care", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Visa Inc.", "ticker": "V", "country": "USA", "sector": "Information Technology", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Procter & Gamble", "ticker": "PG", "country": "USA", "sector": "Consumer Staples", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "ExxonMobil", "ticker": "XOM", "country": "USA", "sector": "Energy", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Chevron Corporation", "ticker": "CVX", "country": "USA", "sector": "Energy", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "JPMorgan Chase & Co.", "ticker": "JPM", "country": "USA", "sector": "Financials", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Walmart Inc.", "ticker": "WMT", "country": "USA", "sector": "Consumer Staples", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Pfizer Inc.", "ticker": "PFE", "country": "USA", "sector": "Health Care", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Coca-Cola Company", "ticker": "KO", "country": "USA", "sector": "Consumer Staples", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Intel Corporation", "ticker": "INTC", "country": "USA", "sector": "Information Technology",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "PepsiCo, Inc.", "ticker": "PEP", "country": "USA", "sector": "Consumer Staples", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "AbbVie Inc.", "ticker": "ABBV", "country": "USA", "sector": "Health Care", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Cisco Systems, Inc.", "ticker": "CSCO", "country": "USA", "sector": "Information Technology",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Oracle Corporation", "ticker": "ORCL", "country": "USA", "sector": "Information Technology",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Abbott Laboratories", "ticker": "ABT", "country": "USA", "sector": "Health Care", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Merck & Co., Inc.", "ticker": "MRK", "country": "USA", "sector": "Health Care", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Home Depot, Inc.", "ticker": "HD", "country": "USA", "sector": "Consumer Discretionary",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Nike, Inc.", "ticker": "NKE", "country": "USA", "sector": "Consumer Discretionary", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Walt Disney Company", "ticker": "DIS", "country": "USA", "sector": "Communication Services",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "AT&T Inc.", "ticker": "T", "country": "USA", "sector": "Communication Services", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Verizon Communications Inc.", "ticker": "VZ", "country": "USA", "sector": "Communication Services",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Lockheed Martin Corporation", "ticker": "LMT", "country": "USA", "sector": "Industrials",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "3M Company", "ticker": "MMM", "country": "USA", "sector": "Industrials", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Caterpillar Inc.", "ticker": "CAT", "country": "USA", "sector": "Industrials", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "UnitedHealth Group", "ticker": "UNH", "country": "USA", "sector": "Health Care", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "CVS Health Corporation", "ticker": "CVS", "country": "USA", "sector": "Health Care", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Bristol-Myers Squibb", "ticker": "BMY", "country": "USA", "sector": "Health Care", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Salesforce, Inc.", "ticker": "CRM", "country": "USA", "sector": "Information Technology",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Adobe Inc.", "ticker": "ADBE", "country": "USA", "sector": "Information Technology", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Qualcomm Incorporated", "ticker": "QCOM", "country": "USA", "sector": "Information Technology",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Texas Instruments Incorporated", "ticker": "TXN", "country": "USA", "sector": "Information Technology",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Advanced Micro Devices, Inc.", "ticker": "AMD", "country": "USA", "sector": "Information Technology",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Intuit Inc.", "ticker": "INTU", "country": "USA", "sector": "Information Technology", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "ServiceNow, Inc.", "ticker": "NOW", "country": "USA", "sector": "Information Technology",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Snowflake Inc.", "ticker": "SNOW", "country": "USA", "sector": "Information Technology",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Palantir Technologies", "ticker": "PLTR", "country": "USA", "sector": "Information Technology",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Square, Inc.", "ticker": "SQ", "country": "USA", "sector": "Information Technology", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Spotify Technology S.A.", "ticker": "SPOT", "country": "USA", "sector": "Communication Services",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Snap Inc.", "ticker": "SNAP", "country": "USA", "sector": "Communication Services", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    # Europe
    {"name": "SAP SE", "ticker": "SAP", "country": "Germany", "sector": "Information Technology", "currency": "EUR",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Novo Nordisk A/S", "ticker": "NOVO-B", "country": "Denmark", "sector": "Health Care", "currency": "DKK",
     "market_cap_bucket": "Mega Cap"},
    {"name": "ASML Holding N.V.", "ticker": "ASML", "country": "Netherlands", "sector": "Information Technology",
     "currency": "EUR", "market_cap_bucket": "Mega Cap"},
    {"name": "LVMH Moët Hennessy Louis Vuitton", "ticker": "MC", "country": "France",
     "sector": "Consumer Discretionary", "currency": "EUR", "market_cap_bucket": "Mega Cap"},
    {"name": "Hermès International", "ticker": "RMS", "country": "France", "sector": "Consumer Discretionary",
     "currency": "EUR", "market_cap_bucket": "Mega Cap"},
    {"name": "Nestlé S.A.", "ticker": "NESN", "country": "Switzerland", "sector": "Consumer Staples", "currency": "CHF",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Roche Holding AG", "ticker": "ROG", "country": "Switzerland", "sector": "Health Care", "currency": "CHF",
     "market_cap_bucket": "Mega Cap"},
    {"name": "AstraZeneca PLC", "ticker": "AZN", "country": "United Kingdom", "sector": "Health Care",
     "currency": "GBP", "market_cap_bucket": "Mega Cap"},
    {"name": "Shell PLC", "ticker": "SHEL", "country": "United Kingdom", "sector": "Energy", "currency": "GBP",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Novartis AG", "ticker": "NOVN", "country": "Switzerland", "sector": "Health Care", "currency": "CHF",
     "market_cap_bucket": "Mega Cap"},
    {"name": "L’Oréal S.A.", "ticker": "OR", "country": "France", "sector": "Consumer Staples", "currency": "EUR",
     "market_cap_bucket": "Mega Cap"},
    {"name": "TotalEnergies SE", "ticker": "TOTF", "country": "France", "sector": "Energy", "currency": "EUR",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Inditex S.A.", "ticker": "ITX", "country": "Spain", "sector": "Consumer Discretionary", "currency": "EUR",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Unilever PLC", "ticker": "ULVR", "country": "United Kingdom", "sector": "Consumer Staples",
     "currency": "GBP", "market_cap_bucket": "Mega Cap"},
    {"name": "HSBC Holdings PLC", "ticker": "HSBA", "country": "United Kingdom", "sector": "Financials",
     "currency": "GBP", "market_cap_bucket": "Mega Cap"},
    {"name": "Siemens AG", "ticker": "SIE", "country": "Germany", "sector": "Industrials", "currency": "EUR",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Deutsche Telekom AG", "ticker": "DTE", "country": "Germany", "sector": "Communication Services",
     "currency": "EUR", "market_cap_bucket": "Mega Cap"},
    {"name": "Sanofi S.A.", "ticker": "SAN", "country": "France", "sector": "Health Care", "currency": "EUR",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Schneider Electric SE", "ticker": "SU", "country": "France", "sector": "Industrials", "currency": "EUR",
     "market_cap_bucket": "Mega Cap"},
    # Asia
    {"name": "Taiwan Semiconductor Manufacturing Company", "ticker": "TSM", "country": "Taiwan",
     "sector": "Information Technology", "currency": "TWD", "market_cap_bucket": "Mega Cap"},
    {"name": "Tencent Holdings Ltd.", "ticker": "TCEHY", "country": "China", "sector": "Communication Services",
     "currency": "HKD", "market_cap_bucket": "Mega Cap"},
    {"name": "Alibaba Group Holding Ltd.", "ticker": "BABA", "country": "China", "sector": "Consumer Discretionary",
     "currency": "HKD", "market_cap_bucket": "Mega Cap"},
    {"name": "Samsung Electronics Co., Ltd.", "ticker": "005930.KS", "country": "South Korea",
     "sector": "Information Technology", "currency": "KRW", "market_cap_bucket": "Mega Cap"},
    {"name": "Reliance Industries Limited", "ticker": "RELIANCE", "country": "India", "sector": "Energy",
     "currency": "INR", "market_cap_bucket": "Mega Cap"},
    {"name": "Toyota Motor Corporation", "ticker": "7203.T", "country": "Japan", "sector": "Consumer Discretionary",
     "currency": "JPY", "market_cap_bucket": "Mega Cap"},
    {"name": "ICBC (Industrial and Commercial Bank of China)", "ticker": "1398.HK", "country": "China",
     "sector": "Financials", "currency": "HKD", "market_cap_bucket": "Mega Cap"},
    {"name": "Kweichow Moutai Co., Ltd.", "ticker": "600519.SS", "country": "China", "sector": "Consumer Staples",
     "currency": "CNY", "market_cap_bucket": "Mega Cap"},
    {"name": "HDFC Bank Limited", "ticker": "HDB", "country": "India", "sector": "Financials", "currency": "INR",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Sony Group Corporation", "ticker": "6758.T", "country": "Japan", "sector": "Communication Services",
     "currency": "JPY", "market_cap_bucket": "Mega Cap"},
    {"name": "Honda Motor Co., Ltd.", "ticker": "7267.T", "country": "Japan", "sector": "Consumer Discretionary",
     "currency": "JPY", "market_cap_bucket": "Mega Cap"},
    {"name": "China Construction Bank Corporation", "ticker": "0939.HK", "country": "China", "sector": "Financials",
     "currency": "HKD", "market_cap_bucket": "Mega Cap"},
    {"name": "Bank of China Limited", "ticker": "3988.HK", "country": "China", "sector": "Financials",
     "currency": "HKD", "market_cap_bucket": "Mega Cap"},
    {"name": "Tata Consultancy Services", "ticker": "TCS", "country": "India", "sector": "Information Technology",
     "currency": "INR", "market_cap_bucket": "Mega Cap"},
    {"name": "MUFG (Mitsubishi UFJ Financial Group)", "ticker": "8306.T", "country": "Japan", "sector": "Financials",
     "currency": "JPY", "market_cap_bucket": "Mega Cap"},
    {"name": "Keyence Corporation", "ticker": "6861.T", "country": "Japan", "sector": "Information Technology",
     "currency": "JPY", "market_cap_bucket": "Mega Cap"},
    {"name": "China Mobile Limited", "ticker": "0941.HK", "country": "China", "sector": "Communication Services",
     "currency": "HKD", "market_cap_bucket": "Mega Cap"},
    {"name": "Ping An Insurance (Group) Company of China", "ticker": "2318.HK", "country": "China",
     "sector": "Financials", "currency": "HKD", "market_cap_bucket": "Mega Cap"},
    {"name": "China Petroleum & Chemical Corporation (Sinopec)", "ticker": "0386.HK", "country": "China",
     "sector": "Energy", "currency": "HKD", "market_cap_bucket": "Mega Cap"},
    # Latin America
    {"name": "Petrobras", "ticker": "PBR", "country": "Brazil", "sector": "Energy", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "America Movil", "ticker": "AMX", "country": "Mexico", "sector": "Communication Services",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Itaú Unibanco", "ticker": "ITUB", "country": "Brazil", "sector": "Financials", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Vale S.A.", "ticker": "VALE", "country": "Brazil", "sector": "Materials", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Banco Bradesco", "ticker": "BBD", "country": "Brazil", "sector": "Financials", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Credicorp", "ticker": "BAP", "country": "Peru", "sector": "Financials", "currency": "USD",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Mercado Libre", "ticker": "MELI", "country": "Argentina", "sector": "Consumer Discretionary",
     "currency": "USD", "market_cap_bucket": "Mega Cap"},
    {"name": "Grupo México", "ticker": "GMEXICOB", "country": "Mexico", "sector": "Materials", "currency": "MXN",
     "market_cap_bucket": "Mega Cap"},
    {"name": "Petrobras Distribuidora", "ticker": "BRDT3", "country": "Brazil", "sector": "Energy", "currency": "BRL",
     "market_cap_bucket": "Large Cap"},
    {"name": "Fomento Económico Mexicano (FEMSA)", "ticker": "FOMENTO", "country": "Mexico",
     "sector": "Consumer Staples", "currency": "MXN", "market_cap_bucket": "Large Cap"}
]

start_prices = {'005930.KS': 100,
                '0386.HK': 100,
                '0939.HK': 100,
                '0941.HK': 100,
                '1398.HK': 100,
                '2222.SR': 23.1,
                '2318.HK': 100,
                '3988.HK': 100,
                '600519.SS': 100,
                '6758.T': 100,
                '6861.T': 100,
                '7203.T': 100,
                '7267.T': 100,
                '8306.T': 100,
                'AAPL': 230.0,
                'ABBV': 220.2,
                'ABT': 132.6,
                'ADBE': 350.5,
                'AMD': 155.7,
                'AMX': 20.2,
                'AMZN': 229.9,
                'ASML': 804.2,
                'AVGO': 359.6,
                'AZN': 81.1,
                'BABA': 155.4,
                'BAP': 266.6,
                'BBD': 3.2,
                'BMY': 47.5,
                'BRDT3': 100,
                'BRK.A': 100,
                'CAT': 431.4,
                'CRM': 246.3,
                'CSCO': 67.7,
                'CVS': 74.7,
                'CVX': 158.2,
                'DIS': 117.1,
                'DTE': 136.8,
                'FOMENTO': 100,
                'GMEXICOB': 100,
                'GOOG': 240.8,
                'HD': 423.4,
                'HDB': 35.4,
                'HSBA': 100,
                'INTC': 24.6,
                'INTU': 660.5,
                'ITUB': 7.1,
                'ITX': 100,
                'JNJ': 178.5,
                'JPM': 305.6,
                'KO': 67.6,
                'LMT': 470.7,
                'MC': 75.7,
                'MELI': 2338.2,
                'META': 750.9,
                'MMM': 159.5,
                'MRK': 85.2,
                'MSFT': 501.0,
                'NESN': 100,
                'NKE': 74.3,
                'NOVN': 100,
                'NOVO-B': 100,
                'NOW': 938.3,
                'NVDA': 177.2,
                'OR': 35.9,
                'ORCL': 307.9,
                'PBR': 12.7,
                'PEP': 144.2,
                'PFE': 24.9,
                'PG': 158.6,
                'PLTR': 164.4,
                'QCOM': 161.5,
                'RELIANCE': 1395,
                'RMS': 2100,
                'ROG': 83.9,
                'SAN': 10.1,
                'SAP': 258.2,
                'SHEL': 72.0,
                'SIE': 100,
                'SNAP': 7.3,
                'SNOW': 224.5,
                'SPOT': 690.3,
                'SQ': 100,
                'SU': 42.0,
                'T': 29.5,
                'TCEHY': 82.1,
                'TCS': 3113,
                'TOTF': 100,
                'TSLA': 368.8,
                'TSM': 258.9,
                'TXN': 184.4,
                'ULVR': 4700,
                'UNH': 353.6,
                'V': 343.5,
                'VALE': 10.6,
                'VZ': 44.1,
                'WMT': 102.7,
                'XOM': 112.1
                }

start_fx_to_usd = {
    "USD": 1 / 1,
    "SAR": 1 / 3.75,  # Saudi Riyal
    "TWD": 1 / 30.00,  # New Taiwan Dollar
    "EUR": 1 / 0.8522,  # Euro
    "DKK": 1 / 6.87,  # Danish Krone
    "CHF": 1 / 0.9180,  # Swiss Franc
    "GBP": 1 / 0.7377,  # British Pound
    "HKD": 1 / 7.7823,  # Hong Kong Dollar
    "KRW": 1 / 1477.50,  # South Korean Won
    "INR": 1 / 88.247,  # Indian Rupee
    "JPY": 1 / 147.75,  # Japanese Yen
    "CNY": 1 / 7.1214,  # Chinese Yuan Renminbi
    "MXN": 1 / 18.471,  # Mexican Peso
    "BRL": 1 / 5.20,  # Brazilian Real
}